Pan4533
moka-guys/mokabed pull request #238
Opened 2021-07-05 23:15 UTC by natashapinto

2021-07-06 12:23 UTC, aledj2 requested changes

2021-07-06 12:23 UTC, aledj2 commented on LiveBedfiles/RequestForms/Pan4566.csv
> +5. b) If specific transcripts are to be used have you provided multiple transcripts for the same gene? (if Yes please state),No,,,,,,,,,
yes.

2021-07-06 12:23 UTC, aledj2 commented on LiveBedfiles/RequestForms/Pan4533.csv
> +5. b) If specific transcripts are to be used have you provided multiple transcripts for the same gene? (if Yes please state),No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
yes

2021-07-06 12:23 UTC, aledj2 commented on LiveBedfiles/Pan4533dataRefSeqFormat.txt
> +#bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonSEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
should this file be deleted considering it doesn't have all regions?

2021-07-06 12:23 UTC, aledj2 commented on LiveBedfiles/Pan4566dataRefSeqFormat.txt
> +#bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonSEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
should this be deleted as it's incomplete?

2021-07-06 14:14 UTC, natashapinto reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/238)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @aledj2)

___
*[LiveBedfiles/Pan4566dataRefSeqFormat.txt, line 1 at r1](https://reviewable.io/reviews/moka-guys/mokabed/238#-MdsxCOsKvLB9lcJdZqN-r1-1:-Mdw9mny7O9-vGAewVum:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/5da3451f493e1077eea8863ca99ab38186a69400/LiveBedfiles/Pan4566dataRefSeqFormat.txt#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

should this be deleted as it's incomplete?
</blockquote></details>

Done.
___
*[LiveBedfiles/Pan4533dataRefSeqFormat.txt, line 1 at r1](https://reviewable.io/reviews/moka-guys/mokabed/238#-MdsxCOsKvLB9lcJdZqJ-r1-1:-Mdw9o060sthPHsAnA6d:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/5da3451f493e1077eea8863ca99ab38186a69400/LiveBedfiles/Pan4533dataRefSeqFormat.txt#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

should this file be deleted considering it doesn't have all regions?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-06 15:08 UTC, aledj2 reviewed
> Reviewed 3 of 14 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/238)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @aledj2)



<!-- Sent from Reviewable.io -->

2021-07-12 12:27 UTC, aledj2 commented on LiveBedfiles/Pan4566dataRefSeqFormat.txt
> +#bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonSEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
this is still here (I think)

2021-07-12 12:27 UTC, aledj2 commented on LiveBedfiles/RequestForms/Pan4566.csv
> +5. b) If specific transcripts are to be used have you provided multiple transcripts for the same gene? (if Yes please state),No,,,,,,,,,
not changed

2021-07-12 16:12 UTC, aledj2 approved these changes

2021-07-12 16:13 UTC, merged

2021-07-12 16:13 UTC, aledj2 commented
This covered Pan4533 and Pan4566